#ifndef GUARD_LSL_COMPILER_LIBINFO_HH_INCLUDED
#define GUARD_LSL_COMPILER_LIBINFO_HH_INCLUDED

#include <lsl/runtime/types.hh>

struct LibInfo {
    char const * Name;
    lsl::runtime::ValueType Returns;
    std::vector<lsl::runtime::ValueType> Parameters;
    bool godonly;
};

static LibInfo const LibInfoData[] = {
    {"llSin", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Float}, false},
    {"llCos", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Float}, false},
    {"llTan", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Float}, false},
    {"llAtan2", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float}, false},
    {"llSqrt", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Float}, false},
    {"llPow", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float}, false},
    {"llAbs", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer}, false},
    {"llFabs", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Float}, false},
    {"llFrand", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Float}, false},
    {"llFloor", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Float}, false},
    {"llCeil", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Float}, false},
    {"llRound", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Float}, false},
    {"llVecMag", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Vector}, false},
    {"llVecNorm", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Vector}, false},
    {"llVecDist", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector}, false},
    {"llRot2Euler", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Rotation}, false},
    {"llEuler2Rot", lsl::runtime::ValueType::Rotation, {lsl::runtime::ValueType::Vector}, false},
    {"llAxes2Rot", lsl::runtime::ValueType::Rotation, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector}, false},
    {"llRot2Fwd", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Rotation}, false},
    {"llRot2Left", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Rotation}, false},
    {"llRot2Up", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Rotation}, false},
    {"llRotBetween", lsl::runtime::ValueType::Rotation, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector}, false},
    {"llWhisper", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::String}, false},
    {"llSay", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::String}, false},
    {"llShout", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::String}, false},
    {"llListen", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"llListenControl", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llListenRemove", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llSensor", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float}, false},
    {"llSensorRepeat", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float}, false},
    {"llSensorRemove", lsl::runtime::ValueType::Void, {}, false},
    {"llDetectedName", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::Integer}, false},
    {"llDetectedKey", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::Integer}, false},
    {"llDetectedOwner", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::Integer}, false},
    {"llDetectedType", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer}, false},
    {"llDetectedPos", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Integer}, false},
    {"llDetectedVel", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Integer}, false},
    {"llDetectedGrab", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Integer}, false},
    {"llDetectedRot", lsl::runtime::ValueType::Rotation, {lsl::runtime::ValueType::Integer}, false},
    {"llDetectedGroup", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer}, false},
    {"llDetectedLinkNumber", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer}, false},
    {"llDie", lsl::runtime::ValueType::Void, {}, false},
    {"llGround", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Vector}, false},
    {"llCloud", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Vector}, false},
    {"llWind", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Vector}, false},
    {"llSetStatus", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llGetStatus", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer}, false},
    {"llSetScale", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector}, false},
    {"llGetScale", lsl::runtime::ValueType::Vector, {}, false},
    {"llSetColor", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Integer}, false},
    {"llGetAlpha", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Integer}, false},
    {"llSetAlpha", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Integer}, false},
    {"llGetColor", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Integer}, false},
    {"llSetTexture", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"llScaleTexture", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Integer}, false},
    {"llOffsetTexture", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Integer}, false},
    {"llRotateTexture", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Integer}, false},
    {"llGetTexture", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::Integer}, false},
    {"llSetPos", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector}, false},
    {"llGetPos", lsl::runtime::ValueType::Vector, {}, false},
    {"llGetLocalPos", lsl::runtime::ValueType::Vector, {}, false},
    {"llSetRot", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Rotation}, false},
    {"llGetRot", lsl::runtime::ValueType::Rotation, {}, false},
    {"llGetLocalRot", lsl::runtime::ValueType::Rotation, {}, false},
    {"llSetForce", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Integer}, false},
    {"llGetForce", lsl::runtime::ValueType::Vector, {}, false},
    {"llTarget", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Float}, false},
    {"llTargetRemove", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llRotTarget", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Rotation, lsl::runtime::ValueType::Float}, false},
    {"llRotTargetRemove", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llMoveToTarget", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Float}, false},
    {"llStopMoveToTarget", lsl::runtime::ValueType::Void, {}, false},
    {"llApplyImpulse", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Integer}, false},
    {"llApplyRotationalImpulse", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Integer}, false},
    {"llSetTorque", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Integer}, false},
    {"llGetTorque", lsl::runtime::ValueType::Vector, {}, false},
    {"llSetForceAndTorque", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Integer}, false},
    {"llGetVel", lsl::runtime::ValueType::Vector, {}, false},
    {"llGetAccel", lsl::runtime::ValueType::Vector, {}, false},
    {"llGetOmega", lsl::runtime::ValueType::Vector, {}, false},
    {"llGetTimeOfDay", lsl::runtime::ValueType::Float, {}, false},
    {"llGetWallclock", lsl::runtime::ValueType::Float, {}, false},
    {"llGetTime", lsl::runtime::ValueType::Float, {}, false},
    {"llResetTime", lsl::runtime::ValueType::Void, {}, false},
    {"llGetAndResetTime", lsl::runtime::ValueType::Float, {}, false},
    {"llSound", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llPlaySound", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Float}, false},
    {"llLoopSound", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Float}, false},
    {"llLoopSoundMaster", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Float}, false},
    {"llLoopSoundSlave", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Float}, false},
    {"llPlaySoundSlave", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Float}, false},
    {"llTriggerSound", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Float}, false},
    {"llStopSound", lsl::runtime::ValueType::Void, {}, false},
    {"llPreloadSound", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"llGetSubString", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llDeleteSubString", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llInsertString", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::String}, false},
    {"llToUpper", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String}, false},
    {"llToLower", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String}, false},
    {"llGiveMoney", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Integer}, false},
    {"llMakeExplosion", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Vector}, false},
    {"llMakeFountain", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Float}, false},
    {"llMakeSmoke", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Vector}, false},
    {"llMakeFire", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Vector}, false},
    {"llRezObject", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Rotation, lsl::runtime::ValueType::Integer}, false},
    {"llLookAt", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float}, false},
    {"llStopLookAt", lsl::runtime::ValueType::Void, {}, false},
    {"llSetTimerEvent", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float}, false},
    {"llSleep", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float}, false},
    {"llGetMass", lsl::runtime::ValueType::Float, {}, false},
    {"llCollisionFilter", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Integer}, false},
    {"llTakeControls", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llReleaseControls", lsl::runtime::ValueType::Void, {}, false},
    {"llAttachToAvatar", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llDetachFromAvatar", lsl::runtime::ValueType::Void, {}, false},
    {"llTakeCamera", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key}, false},
    {"llReleaseCamera", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key}, false},
    {"llGetOwner", lsl::runtime::ValueType::Key, {}, false},
    {"llInstantMessage", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"llEmail", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"llGetNextEmail", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"llGetKey", lsl::runtime::ValueType::Key, {}, false},
    {"llSetBuoyancy", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float}, false},
    {"llSetHoverHeight", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float}, false},
    {"llStopHover", lsl::runtime::ValueType::Void, {}, false},
    {"llMinEventDelay", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float}, false},
    {"llSoundPreload", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"llRotLookAt", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Rotation, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float}, false},
    {"llStringLength", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::String}, false},
    {"llStartAnimation", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"llStopAnimation", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"llPointAt", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector}, false},
    {"llStopPointAt", lsl::runtime::ValueType::Void, {}, false},
    {"llTargetOmega", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float}, false},
    {"llGetStartParameter", lsl::runtime::ValueType::Integer, {}, false},
    {"llGodLikeRezObject", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Vector}, true},
    {"llRequestPermissions", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Integer}, false},
    {"llGetPermissionsKey", lsl::runtime::ValueType::Key, {}, false},
    {"llGetPermissions", lsl::runtime::ValueType::Integer, {}, false},
    {"llGetLinkNumber", lsl::runtime::ValueType::Integer, {}, false},
    {"llSetLinkColor", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Integer}, false},
    {"llCreateLink", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Integer}, false},
    {"llBreakLink", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llBreakAllLinks", lsl::runtime::ValueType::Void, {}, false},
    {"llGetLinkKey", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::Integer}, false},
    {"llGetLinkName", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::Integer}, false},
    {"llGetInventoryNumber", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer}, false},
    {"llGetInventoryName", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llSetScriptState", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"llGetEnergy", lsl::runtime::ValueType::Float, {}, false},
    {"llGiveInventory", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"llRemoveInventory", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"llSetText", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Float}, false},
    {"llWater", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Vector}, false},
    {"llPassTouches", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llRequestAgentData", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Integer}, false},
    {"llRequestInventoryData", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::String}, false},
    {"llSetDamage", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float}, false},
    {"llTeleportAgentHome", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key}, false},
    {"llModifyLand", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llCollisionSound", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Float}, false},
    {"llCollisionSprite", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"llGetAnimation", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::Key}, false},
    {"llResetScript", lsl::runtime::ValueType::Void, {}, false},
    {"llMessageLinked", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Key}, false},
    {"llPushObject", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Integer}, false},
    {"llPassCollisions", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llGetScriptName", lsl::runtime::ValueType::String, {}, false},
    {"llGetNumberOfSides", lsl::runtime::ValueType::Integer, {}, false},
    {"llAxisAngle2Rot", lsl::runtime::ValueType::Rotation, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Float}, false},
    {"llRot2Axis", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Rotation}, false},
    {"llRot2Angle", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Rotation}, false},
    {"llAcos", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Float}, false},
    {"llAsin", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Float}, false},
    {"llAngleBetween", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Rotation, lsl::runtime::ValueType::Rotation}, false},
    {"llGetInventoryKey", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::String}, false},
    {"llAllowInventoryDrop", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llGetSunDirection", lsl::runtime::ValueType::Vector, {}, false},
    {"llGetTextureOffset", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Integer}, false},
    {"llGetTextureScale", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Integer}, false},
    {"llGetTextureRot", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Integer}, false},
    {"llSubStringIndex", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"llGetOwnerKey", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::Key}, false},
    {"llGetCenterOfMass", lsl::runtime::ValueType::Vector, {}, false},
    {"llListSort", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llGetListLength", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::List}, false},
    {"llList2Integer", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer}, false},
    {"llList2Float", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer}, false},
    {"llList2String", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer}, false},
    {"llList2Key", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer}, false},
    {"llList2Vector", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer}, false},
    {"llList2Rot", lsl::runtime::ValueType::Rotation, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer}, false},
    {"llList2List", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llDeleteSubList", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llGetListEntryType", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer}, false},
    {"llList2CSV", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::List}, false},
    {"llCSV2List", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::String}, false},
    {"llListRandomize", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer}, false},
    {"llList2ListStrided", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llGetRegionCorner", lsl::runtime::ValueType::Vector, {}, false},
    {"llListInsertList", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer}, false},
    {"llListFindList", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::List}, false},
    {"llGetObjectName", lsl::runtime::ValueType::String, {}, false},
    {"llSetObjectName", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"llGetDate", lsl::runtime::ValueType::String, {}, false},
    {"llEdgeOfWorld", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector}, false},
    {"llGetAgentInfo", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Key}, false},
    {"llAdjustSoundVolume", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float}, false},
    {"llSetSoundQueueing", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llSetSoundRadius", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float}, false},
    {"llKey2Name", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::Key}, false},
    {"llSetTextureAnim", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float}, false},
    {"llTriggerSoundLimited", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector}, false},
    {"llEjectFromLand", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key}, false},
    {"llParseString2List", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::List, lsl::runtime::ValueType::List}, false},
    {"llOverMyLand", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Key}, false},
    {"llGetLandOwnerAt", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::Vector}, false},
    {"llGetNotecardLine", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"llGetAgentSize", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Key}, false},
    {"llSameGroup", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Key}, false},
    {"llUnSit", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key}, false},
    {"llGroundSlope", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Vector}, false},
    {"llGroundNormal", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Vector}, false},
    {"llGroundContour", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Vector}, false},
    {"llGetAttached", lsl::runtime::ValueType::Integer, {}, false},
    {"llGetFreeMemory", lsl::runtime::ValueType::Integer, {}, false},
    {"llGetRegionName", lsl::runtime::ValueType::String, {}, false},
    {"llGetRegionTimeDilation", lsl::runtime::ValueType::Float, {}, false},
    {"llGetRegionFPS", lsl::runtime::ValueType::Float, {}, false},
    {"llParticleSystem", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::List}, false},
    {"llGroundRepel", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float}, false},
    {"llGiveInventoryList", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::List}, false},
    {"llSetVehicleType", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llSetVehicleFloatParam", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float}, false},
    {"llSetVehicleVectorParam", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Vector}, false},
    {"llSetVehicleRotationParam", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Rotation}, false},
    {"llSetVehicleFlags", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llRemoveVehicleFlags", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llSitTarget", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Rotation}, false},
    {"llAvatarOnSitTarget", lsl::runtime::ValueType::Key, {}, false},
    {"llAddToLandPassList", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Float}, false},
    {"llSetTouchText", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"llSetSitText", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"llSetCameraEyeOffset", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector}, false},
    {"llSetCameraAtOffset", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector}, false},
    {"llDumpList2String", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::String}, false},
    {"llScriptDanger", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Vector}, false},
    {"llDialog", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer}, false},
    {"llVolumeDetect", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llResetOtherScript", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"llGetScriptState", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::String}, false},
    {"llRemoteLoadScript", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llSetRemoteScriptAccessPin", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llRemoteLoadScriptPin", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llOpenRemoteDataChannel", lsl::runtime::ValueType::Void, {}, false},
    {"llSendRemoteData", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::String}, false},
    {"llRemoteDataReply", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"llCloseRemoteDataChannel", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key}, false},
    {"llMD5String", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"llSetPrimitiveParams", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::List}, false},
    {"llStringToBase64", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String}, false},
    {"llBase64ToString", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String}, false},
    {"llXorBase64Strings", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"llRemoteDataSetRegion", lsl::runtime::ValueType::Void, {}, false},
    {"llLog10", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Float}, false},
    {"llLog", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Float}, false},
    {"llGetAnimationList", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::Key}, false},
    {"llSetParcelMusicURL", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"llGetRootPosition", lsl::runtime::ValueType::Vector, {}, false},
    {"llGetRootRotation", lsl::runtime::ValueType::Rotation, {}, false},
    {"llGetObjectDesc", lsl::runtime::ValueType::String, {}, false},
    {"llSetObjectDesc", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"llGetCreator", lsl::runtime::ValueType::Key, {}, false},
    {"llGetTimestamp", lsl::runtime::ValueType::String, {}, false},
    {"llSetLinkAlpha", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Integer}, false},
    {"llGetNumberOfPrims", lsl::runtime::ValueType::Integer, {}, false},
    {"llGetNumberOfNotecardLines", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::String}, false},
    {"llGetBoundingBox", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::Key}, false},
    {"llGetGeometricCenter", lsl::runtime::ValueType::Vector, {}, false},
    {"llGetPrimitiveParams", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::List}, false},
    {"llIntegerToBase64", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::Integer}, false},
    {"llBase64ToInteger", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::String}, false},
    {"llGetGMTclock", lsl::runtime::ValueType::Float, {}, false},
    {"llGetSimulatorHostname", lsl::runtime::ValueType::String, {}, false},
    {"llSetLocalRot", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Rotation}, false},
    {"llParseStringKeepNulls", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::List, lsl::runtime::ValueType::List}, false},
    {"llRezAtRoot", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Rotation, lsl::runtime::ValueType::Integer}, false},
    {"llGetObjectPermMask", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer}, false},
    {"llSetObjectPermMask", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, true},
    {"llGetInventoryPermMask", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"llSetInventoryPermMask", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, true},
    {"llGetInventoryCreator", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::String}, false},
    {"llOwnerSay", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"llRequestSimulatorData", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"llForceMouselook", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llGetObjectMass", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Key}, false},
    {"llListReplaceList", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llLoadURL", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"llParcelMediaCommandList", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::List}, false},
    {"llParcelMediaQuery", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::List}, false},
    {"llModPow", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llGetInventoryType", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::String}, false},
    {"llSetPayPrice", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::List}, false},
    {"llGetCameraPos", lsl::runtime::ValueType::Vector, {}, false},
    {"llGetCameraRot", lsl::runtime::ValueType::Rotation, {}, false},
    {"llSetPrimURL", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"llRefreshPrimURL", lsl::runtime::ValueType::Void, {}, false},
    {"llEscapeURL", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String}, false},
    {"llUnescapeURL", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String}, false},
    {"llMapDestination", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector}, false},
    {"llAddToLandBanList", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Float}, false},
    {"llRemoveFromLandPassList", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key}, false},
    {"llRemoveFromLandBanList", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key}, false},
    {"llSetCameraParams", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::List}, false},
    {"llClearCameraParams", lsl::runtime::ValueType::Void, {}, false},
    {"llListStatistics", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::List}, false},
    {"llGetUnixTime", lsl::runtime::ValueType::Integer, {}, false},
    {"llGetParcelFlags", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Vector}, false},
    {"llGetRegionFlags", lsl::runtime::ValueType::Integer, {}, false},
    {"llXorBase64StringsCorrect", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"llHTTPRequest", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::List, lsl::runtime::ValueType::String}, false},
    {"llResetLandBanList", lsl::runtime::ValueType::Void, {}, false},
    {"llResetLandPassList", lsl::runtime::ValueType::Void, {}, false},
    {"llGetObjectPrimCount", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Key}, false},
    {"llGetParcelPrimOwners", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::Vector}, false},
    {"llGetParcelPrimCount", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llGetParcelMaxPrims", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Integer}, false},
    {"llGetParcelDetails", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::List}, false},
    {"llSetLinkPrimitiveParams", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::List}, false},
    {"llSetLinkTexture", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"llStringTrim", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"llRegionSay", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::String}, false},
    {"llGetObjectDetails", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::List}, false},
    {"llSetClickAction", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llGetRegionAgentCount", lsl::runtime::ValueType::Integer, {}, false},
    {"llTextBox", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"llGetAgentLanguage", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::Key}, false},
    {"llDetectedTouchUV", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Integer}, false},
    {"llDetectedTouchFace", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer}, false},
    {"llDetectedTouchPos", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Integer}, false},
    {"llDetectedTouchNormal", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Integer}, false},
    {"llDetectedTouchBinormal", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Integer}, false},
    {"llDetectedTouchST", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Integer}, false},
    {"llSHA1String", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String}, false},
    {"llGetFreeURLs", lsl::runtime::ValueType::Integer, {}, false},
    {"llRequestURL", lsl::runtime::ValueType::Key, {}, false},
    {"llRequestSecureURL", lsl::runtime::ValueType::Key, {}, false},
    {"llReleaseURL", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"llHTTPResponse", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::String}, false},
    {"llGetHTTPHeader", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"llSetPrimMediaParams", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::List}, false},
    {"llGetPrimMediaParams", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::List}, false},
    {"llClearPrimMedia", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer}, false},
    {"llSetLinkPrimitiveParamsFast", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::List}, false},
    {"llGetLinkPrimitiveParams", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::List}, false},
    {"llLinkParticleSystem", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::List}, false},
    {"llSetLinkTextureAnim", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float}, false},
    {"llGetLinkNumberOfSides", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer}, false},
    {"llGetUsername", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::Key}, false},
    {"llRequestUsername", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::Key}, false},
    {"llGetDisplayName", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::Key}, false},
    {"llRequestDisplayName", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::Key}, false},
    {"llGetEnv", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String}, false},
    {"llRegionSayTo", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::String}, false},
    {"llSetMemoryLimit", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer}, false},
    {"llGetMemoryLimit", lsl::runtime::ValueType::Integer, {}, false},
    {"llSetLinkMedia", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::List}, false},
    {"llGetLinkMedia", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::List}, false},
    {"llClearLinkMedia", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"llSetLinkCamera", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector}, false},
    {"llSetContentType", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Integer}, false},
    {"llLinkSitTarget", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Rotation}, false},
    {"llAvatarOnLinkSitTarget", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::Integer}, false},
    {"llSetVelocity", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Integer}, false},
    {"llCastRay", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::List}, false},
    {"llGetMassMKS", lsl::runtime::ValueType::Float, {}, false},
    {"llSetPhysicsMaterial", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float}, false},
    {"llGetPhysicsMaterial", lsl::runtime::ValueType::List, {}, false},
    {"llManageEstateAccess", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Key}, false},
    {"llSetKeyframedMotion", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::List}, false},
    {"llTransferLindenDollars", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Integer}, false},
    {"llGetParcelMusicURL", lsl::runtime::ValueType::String, {}, false},
    {"llScriptProfiler", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llGetSPMaxMemory", lsl::runtime::ValueType::Integer, {}, false},
    {"llGetUsedMemory", lsl::runtime::ValueType::Integer, {}, false},
    {"llSetAngularVelocity", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Integer}, false},
    {"llSetRegionPos", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Vector}, false},
    {"llGetAgentList", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::List}, false},
    {"llAttachToAvatarTemp", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"llTeleportAgent", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector}, false},
    {"llTeleportAgentGlobalCoords", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector}, false},
    {"llGenerateKey", lsl::runtime::ValueType::Key, {}, false},
    {"llNavigateTo", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::List}, false},
    {"llCreateCharacter", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::List}, false},
    {"llPursue", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::List}, false},
    {"llWanderWithin", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::List}, false},
    {"llFleeFrom", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::List}, false},
    {"llPatrolPoints", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::List}, false},
    {"llExecCharacterCmd", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::List}, false},
    {"llDeleteCharacter", lsl::runtime::ValueType::Void, {}, false},
    {"llUpdateCharacter", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::List}, false},
    {"llEvade", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::List}, false},
    {"llGetClosestNavPoint", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::List}, false},
    {"llGetStaticPath", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::List}, false},
    {"llGetSimStats", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Integer}, false},
    {"llSetAnimationOverride", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"llGetAnimationOverride", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String}, false},
    {"llResetAnimationOverride", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"llJson2List", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::String}, false},
    {"llList2Json", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::List}, false},
    {"llJsonGetValue", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::List}, false},
    {"llJsonSetValue", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::List, lsl::runtime::ValueType::String}, false},
    {"llJsonValueType", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::List}, false},
    {"llReturnObjectsByID", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::List}, false},
    {"llReturnObjectsByOwner", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Integer}, false},
    {"osSetRegionWaterHeight", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float}, false},
    {"osSetRegionSunSettings", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float}, false},
    {"osSetEstateSunSettings", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float}, false},
    {"osGetCurrentSunHour", lsl::runtime::ValueType::Float, {}, false},
    {"osGetSunParam", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::String}, false},
    {"osSetSunParam", lsl::runtime::ValueType::String, {}, false},
    {"osWindActiveModelPluginName", lsl::runtime::ValueType::String, {}, false},
    {"osSetWindParam", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Float}, false},
    {"osGetWindParam", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"osParcelJoin", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector}, false},
    {"osParcelSubdivide", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector}, false},
    {"osSetParcelDetails", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::List}, false},
    {"osList2Double", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer}, false},
    {"osSetDynamicTextureURL", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"osSetDynamicTextureURLBlend", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"osSetDynamicTextureURLBlendFace", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"osSetDynamicTextureData", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"osSetDynamicTextureDataBlend", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"osSetDynamicTextureDataBlendFace", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"osGetTerrainHeight", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"osSetTerrainHeight", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float}, false},
    {"osTerrainFlush", lsl::runtime::ValueType::Void, {}, false},
    {"osRegionRestart", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Float}, false},
    {"osRegionNotice", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"osConsoleCommand", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"osSetParcelMediaURL", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"osSetParcelSIPaddress", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"osSetPrimFloatOnWater", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"osTeleportAgent", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector}, false},
    {"osTeleportOwner", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector}, false},
    {"osGetAgentIP", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::Key}, false},
    {"osGetAgents", lsl::runtime::ValueType::List, {}, false},
    {"osAvatarPlayAnimation", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"osAvatarStopAnimation", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"osForceAttachToAvatar", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer}, false},
    {"osForceAttachToAvatarFromInventory", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"osForceAttachToOtherAvatarFromInventory", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"osForceDetachFromAvatar", lsl::runtime::ValueType::Void, {}, false},
    {"osGetNumberOfAttachments", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::List}, false},
    {"osMessageAttachments", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer}, false},
    {"osMovePen", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"osDrawLine", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"osDrawText", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"osDrawEllipse", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"osDrawRectangle", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"osDrawFilledRectangle", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"osDrawPolygon", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::List, lsl::runtime::ValueType::List}, false},
    {"osDrawFilledPolygon", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::List, lsl::runtime::ValueType::List}, false},
    {"osSetFontSize", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"osSetFontName", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"osSetPenSize", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"osSetPenColor", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"osSetPenCap", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"osDrawImage", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::String}, false},
    {"osGetDrawStringSize", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"osGetScriptEngineName", lsl::runtime::ValueType::String, {}, false},
    {"osGetSimulatorVersion", lsl::runtime::ValueType::String, {}, false},
    {"osParseJSON", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String}, false},
    {"osParseJSONNew", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String}, false},
    {"osMessageObject", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"osMakeNotecard", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::List}, false},
    {"osGetNotecardLine", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"osGetNotecard", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String}, false},
    {"osGetNumberOfNotecardLines", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::String}, false},
    {"osAvatarName2Key", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"osKey2Name", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::Key}, false},
    {"osGetGridNick", lsl::runtime::ValueType::String, {}, false},
    {"osGetGridName", lsl::runtime::ValueType::String, {}, false},
    {"osGetGridLoginURI", lsl::runtime::ValueType::String, {}, false},
    {"osGetGridHomeURI", lsl::runtime::ValueType::String, {}, false},
    {"osGetGridCustom", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::Key}, false},
    {"osFormatString", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::List}, false},
    {"osMatchString", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"osReplaceString", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"osLoadedCreationDate", lsl::runtime::ValueType::String, {}, false},
    {"osLoadedCreationTime", lsl::runtime::ValueType::String, {}, false},
    {"osLoadedCreationID", lsl::runtime::ValueType::String, {}, false},
    {"osGetLinkPrimitiveParams", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::List}, false},
    {"osIsNpc", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::Key}, false},
    {"osNpcCreate", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Key}, false},
    {"osNpcSaveAppearance", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"osNpcLoadAppearance", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"osNpcGetOwner", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::Key}, false},
    {"osNpcGetPos", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::Key}, false},
    {"osNpcMoveTo", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Vector}, false},
    {"osNpcMoveToTarget", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Integer}, false},
    {"osNpcGetRot", lsl::runtime::ValueType::Rotation, {lsl::runtime::ValueType::Key}, false},
    {"osNpcSetRot", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Rotation}, false},
    {"osNpcStopMoveToTarget", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key}, false},
    {"osNpcSay", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"osNpcShout", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"osNpcSit", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Integer}, false},
    {"osNpcStand", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Integer}, false},
    {"osNpcRemove", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key}, false},
    {"osNpcPlayAnimation", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"osNpcStopAnimation", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"osNpcWhisper", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"osNpcTouch", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Integer}, false},
    {"osOwnerSaveAppearance", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"osAgentSaveAppearance", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"osGetMapTexture", lsl::runtime::ValueType::Key, {}, false},
    {"osGetRegionMapTexture", lsl::runtime::ValueType::Key, {lsl::runtime::ValueType::String}, false},
    {"osGetRegionStats", lsl::runtime::ValueType::List, {}, false},
    {"osGetSimulatorMemory", lsl::runtime::ValueType::Integer, {}, false},
    {"osKickAvatar", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"osSetSpeed", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Float}, false},
    {"osGetHealth", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Key}, false},
    {"osCauseDamage", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Float}, false},
    {"osCauseHealing", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Float}, false},
    {"osGetPrimitiveParams", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::List}, false},
    {"osSetPrimitiveParams", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::List}, false},
    {"osSetProjectionParams", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Key, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float}, false},
    {"osGetAvatarList", lsl::runtime::ValueType::List, {}, false},
    {"osUnixTimeToTimestamp", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::Integer}, false},
    {"osGetInventoryDesc", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String}, false},
    {"osInviteToGroup", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer}, false},
    {"osEjectFromGroup", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer}, false},
    {"osSetTerrainTexture", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Key}, false},
    {"osSetTerrainTextureHeight", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float}, false},
    {"osIsUUID", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::String}, false},
    {"osMin", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float}, false},
    {"osMax", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float}, false},
    {"osGetRezzingObject", lsl::runtime::ValueType::Key, {}, false},
    {"osSetContentType", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"osDropAttachment", lsl::runtime::ValueType::Void, {}, false},
    {"osDropAttachmentAt", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Rotation}, false},
    {"osForceDropAttachment", lsl::runtime::ValueType::Void, {}, false},
    {"osForceDropAttachmentAt", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Rotation}, false},
    {"osListenRegex", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"osRegexIsMatch", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"lsGetWindlightScene", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::List}, false},
    {"lsSetWindlightScene", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::List}, false},
    {"lsSetWindlightSceneTargeted", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::Key}, false},
    {"osReturnObject", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key}, false},
    {"osReturnObjects", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float}, false},
    {"osShutDown", lsl::runtime::ValueType::Void, {}, false},
    {"osAddAgentToGroup", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"osRezObject", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Vector, lsl::runtime::ValueType::Rotation, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"aaSetCloudDensity", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float}, false},
    {"aaUpdateDatabase", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"aaQueryDatabase", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"aaSerializeXML", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::List, lsl::runtime::ValueType::List}, false},
    {"aaDeserializeXMLKeys", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::String}, false},
    {"aaDeserializeXMLValues", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::String}, false},
    {"aaSetConeOfSilence", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Float}, false},
    {"aaJoinCombatTeam", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key, lsl::runtime::ValueType::String}, false},
    {"aaLeaveCombat", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key}, false},
    {"aaJoinCombat", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Key}, false},
    {"aaGetHealth", lsl::runtime::ValueType::Float, {lsl::runtime::ValueType::Key}, false},
    {"aaGetTeam", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::Key}, false},
    {"aaGetTeamMembers", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::String}, false},
    {"aaGetLastOwner", lsl::runtime::ValueType::String, {}, false},
    {"aaSayDistance", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::String}, false},
    {"aaSayTo", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"aaGetText", lsl::runtime::ValueType::String, {}, false},
    {"aaGetTextColor", lsl::runtime::ValueType::Rotation, {}, false},
    {"aaRaiseError", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"aaFreezeAvatar", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"aaThawAvatar", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"aaRequestCombatPermission", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"aaGetWalkDisabled", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::String}, false},
    {"aaSetWalkDisabled", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"aaGetFlyDisabled", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::String}, false},
    {"aaSetFlyDisabled", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Float}, false},
    {"aaAvatarFullName2Key", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String}, false},
    {"aaSetEnv", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::List}, false},
    {"aaGetIsInfiniteRegion", lsl::runtime::ValueType::Integer, {}, false},
    {"aaAllRegionInstanceSay", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::String}, false},
    {"aaWindlightGetSceneIsStatic", lsl::runtime::ValueType::Integer, {}, false},
    {"aaWindlightGetSceneDayCycleKeyFrameCount", lsl::runtime::ValueType::Integer, {}, false},
    {"aaWindlightGetDayCycle", lsl::runtime::ValueType::List, {}, false},
    {"aaWindlightAddDayCycleFrame", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Integer}, false},
    {"aaWindlightRemoveDayCycleFrame", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer}, false},
    {"aaWindlightGetScene", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::List}, false},
    {"aaWindlightSetScene", lsl::runtime::ValueType::Integer, {lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::List}, false},
    {"botCreateBot", lsl::runtime::ValueType::String, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Vector}, false},
    {"botGetWaitingTime", lsl::runtime::ValueType::Vector, {lsl::runtime::ValueType::Integer}, false},
    {"botPauseMovement", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"botResumeMovement", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"botSetShouldFly", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer}, false},
    {"botSetMap", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::List, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"botRemoveBot", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"botFollowAvatar", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Float, lsl::runtime::ValueType::Float}, false},
    {"botStopFollowAvatar", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"botSendChatMessage", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Integer, lsl::runtime::ValueType::Integer}, false},
    {"botSendIM", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"botTouchObject", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"botSitObject", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String, lsl::runtime::ValueType::Vector}, false},
    {"botStandUp", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false},
    {"botAddTag", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String, lsl::runtime::ValueType::String}, false},
    {"botGetBotsWithTag", lsl::runtime::ValueType::List, {lsl::runtime::ValueType::String}, false},
    {"botRemoveBotsWithTag", lsl::runtime::ValueType::Void, {lsl::runtime::ValueType::String}, false}
};

#endif //GUARD_LSL_COMPILER_LIBINFO_HH_INCLUDED
