language: cpp
install: sudo apt-get install libboost-dev libsqlite3-dev libboost-filesystem-dev
compiler:
  - gcc
# Change this to your needs
script: ./autogen.sh && ./configure && make

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Uxoa7/n6oSuHp1hv6+VSqjwjkmRowFEIY/FgUvA27khM5XovqFPpO/NzeKmJEka7Dmg8VuwHbn5HzHMzEZmewyxTpXSBSpklJ1O0EyvNVvzp/Mc8xmOf03XAqN0vwcEggaaz0jJjUZrWdyJceA9QFBVlBpLJSF6mVcxgAqlGOM8="

addons:
  coverity_scan:
    project:
      name: "vinzenz/vsqlite--"
      description: "A welldesigned and portable SQLite3 Wrapper for C++"
    notification_email: evilissimo@gmail.com
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: "make -j4"
    branch_pattern: coverity_scan
